export declare function getModelName(model: any): any;
export declare function copy(data: any): any;
export declare function setAttributes(elem: any, attrs: any): any;
export declare function addClass(elem: any, c: any): void;
export declare function toggleClass(elem: any, c: any): void;
export declare function hasClass(elem: any, c: any): boolean;
export declare function removeClass(elem: any, c: any): void;
export declare function emptyElement(elem: any): any;
export declare function removeElement(elem: any, keepChildren: any): any;
export declare function px(val?: number): string;
export declare function makeButton(label: any, attrs: any, callback: any, ctx: any): HTMLDivElement;
export declare function makeInput(options: any, callback: any, ctx: any): HTMLDivElement;
export declare function eventPreventer(elem: any, events: any): void;
export declare function isKeyCode(event: any, kc: any): boolean;
export declare function vecDist(v1: any, v2: any): number;
export declare function vecAdd(v1: any, v2: any, a: any): any[];
export declare function vecEquals(v1: any, v2: any, eps?: number): boolean;
export declare function transformExtent(extent: any, T: any): any;
export declare function projectExtent(extent: any, proj?: any): any;
export declare function unprojectExtent(extent: any, proj?: any): any;
export declare function layerExtent(layer: any): any;
